### ISSUE TITLE
Prototypes

### ISSUE THREAD

**Issue by michaelku1** [AmingWu/Universal-Prototype-Enhancing#4]
Hi Aming, Thanks for sharing the code for your paper. 

I could not seem to find in the code where the universal prototype/conditional prototype are computed. Are they in the code yet? Thanks.

**Comment by AmingWu** [comment]
Thank you very much. The code has been contained in maskrcnn_benchmark, i.e., generalized_rcnn.py, roi_heads.py, box_head.py, and roi_box_feature_extractors.py
![捕获](https://user-images.githubusercontent.com/38445175/146953123-26564f12-8d09-4b53-a783-55a5907db7d5.JPG)
.

**Comment by michaelku1** [comment]
Thank you!
